//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string UR_ID { get; set; }
        public string UR_NAME { get; set; }
        public string UR_PASSWD { get; set; }
        public string CS_ID { get; set; }
        public Nullable<decimal> LN_ID { get; set; }
        public Nullable<decimal> UR_TYPE_ID { get; set; }
        public Nullable<bool> UR_ACTIVE { get; set; }
        public System.DateTime UR_ADDTIME { get; set; }
        public System.DateTime UR_UPTIME { get; set; }
        public string UR_STATUS { get; set; }
    }
}
