//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connections
    {
        public string CCID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Last_Activity_Time { get; set; }
        public string Address { get; set; }
        public Nullable<int> Messaage_Received { get; set; }
        public Nullable<int> Message_Sent { get; set; }
    }
}
