//------------------------------------------------------------------------------
// <auto-generated>
//     姝や唬鐮佸凡浠庢ā鏉跨敓鎴愩€?
//
//     鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳藉鑷村簲鐢ㄧ▼搴忓嚭鐜版剰澶栫殑琛屼负銆?
//     濡傛灉閲嶆柊鐢熸垚浠ｇ爜锛屽皢瑕嗙洊瀵规鏂囦欢鐨勬墜鍔ㄦ洿鏀广€?
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMD
    {
        public string PMDName { get; set; }
        public string IMSI { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public byte[] DeviceInfo { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Connection { get; set; }
        public Nullable<bool> StatsCollection { get; set; }
        public Nullable<int> PMD_ID { get; set; }
        public byte[] CurrentConfiguration { get; set; }
        public string CurrrentConfigurationTime { get; set; }
        public byte[] NewConfiguration { get; set; }
        public string NewConfigurationTime { get; set; }
        public string Clock { get; set; }
        public string FirmwareVersion { get; set; }
        public string NewFirmwareId { get; set; }
        public Nullable<int> NumFirmwareUpdateAttempts { get; set; }
        public Nullable<int> KeepAliveMessageInterval { get; set; }
        public string CS_ID { get; set; }
        public Nullable<byte> HighSpeedAlert { get; set; }
        public Nullable<byte> LowSpeedAlert { get; set; }
        public byte[] PageFileList { get; set; }
        public string CurrentClock { get; set; }
    }
}
